services:
  mcp-woo:
    build: .
    ports:
      - "8200:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: python -m src.server
    networks:
    - cluster

networks:
  cluster:
    external: true